import request from "supertest";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import app from "../src/app.js";
import { registerUser } from "../src/auth/auth.service.js";
import { prisma } from "../src/lib/prisma.js";
let owner; let participant; let ownerAgent; let participantAgent; let quizId; let sessionId; let pin;
beforeAll(async () => { owner = await registerUser(prisma, { email: `session-owner-${Date.now()}@example.com`, password: "password123", displayName: "Session Owner" }); participant = await registerUser(prisma, { email: `session-player-${Date.now()}@example.com`, password: "password123", displayName: "Session Player" }); ownerAgent = request.agent(app); participantAgent = request.agent(app); await ownerAgent.post("/api/auth/login").send({ email: owner.email, password: "password123" }); await participantAgent.post("/api/auth/login").send({ email: participant.email, password: "password123" }); const category = await prisma.category.findFirst(); const quiz = await ownerAgent.post("/api/quizzes").send({ title: "Session quiz", categoryId: category.id, defaultTimeLimitSeconds: 30, defaultPointsPerQuestion: 1000, revealCorrectAnswer: true }); quizId = quiz.body.data.quiz.id; await ownerAgent.post(`/api/quizzes/${quizId}/questions`).send({ text: "Question", type: "SINGLE_CHOICE", options: [{ text: "A", isCorrect: true }, { text: "B", isCorrect: false }] }); await ownerAgent.post(`/api/quizzes/${quizId}/ready`); });
describe("session lobby", () => { it("creates only one session for concurrent requests", async () => { const responses = await Promise.all([ownerAgent.post("/api/sessions").send({ quizId }), ownerAgent.post("/api/sessions").send({ quizId })]); expect(responses.map((response) => response.status).sort()).toEqual([201, 409]); const created = responses.find((response) => response.status === 201); const conflict = responses.find((response) => response.status === 409); expect(conflict.body.error.code).toBe("ACTIVE_SESSION_ALREADY_EXISTS"); sessionId = created.body.data.session.id; pin = created.body.data.session.pin; expect(pin).toMatch(/^\d{6}$/); }); it("supports lookup and idempotent join", async () => { expect((await participantAgent.get(`/api/sessions/by-pin/${pin}`)).status).toBe(200); expect((await participantAgent.post(`/api/sessions/${sessionId}/join`)).status).toBe(200); expect((await participantAgent.post(`/api/sessions/${sessionId}/join`)).body.data.rejoined).toBe(true); expect((await ownerAgent.post(`/api/sessions/${sessionId}/join`)).status).toBe(403); }); it("cancels session", async () => { const r = await ownerAgent.post(`/api/sessions/${sessionId}/cancel`); expect(r.status).toBe(200); }); });
afterAll(async () => { if (sessionId) await prisma.quizSession.delete({ where: { id: sessionId } }); if (quizId) await prisma.quiz.delete({ where: { id: quizId } }); if (owner) await prisma.user.delete({ where: { id: owner.id } }); if (participant) await prisma.user.delete({ where: { id: participant.id } }); await prisma.$disconnect(); });
