import request from "supertest";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import app from "../src/app.js";
import { registerUser } from "../src/auth/auth.service.js";
import { prisma } from "../src/lib/prisma.js";
let owner; let player; let ownerAgent; let playerAgent; let quizId; let sessionId;
beforeAll(async () => { owner = await registerUser(prisma, { email: `leave-owner-${Date.now()}@example.com`, password: "password123", displayName: "Leave Owner" }); player = await registerUser(prisma, { email: `leave-player-${Date.now()}@example.com`, password: "password123", displayName: "Leave Player" }); ownerAgent = request.agent(app); playerAgent = request.agent(app); await ownerAgent.post("/api/auth/login").send({ email: owner.email, password: "password123" }); await playerAgent.post("/api/auth/login").send({ email: player.email, password: "password123" }); const category = await prisma.category.findFirst(); const quiz = await ownerAgent.post("/api/quizzes").send({ title: "Leave test", categoryId: category.id, defaultTimeLimitSeconds: 30, defaultPointsPerQuestion: 1000, revealCorrectAnswer: true }); quizId = quiz.body.data.quiz.id; await ownerAgent.post(`/api/quizzes/${quizId}/questions`).send({ text: "Q", type: "SINGLE_CHOICE", options: [{ text: "A", isCorrect: true }, { text: "B", isCorrect: false }] }); await ownerAgent.post(`/api/quizzes/${quizId}/ready`); const session = await ownerAgent.post("/api/sessions").send({ quizId }); sessionId = session.body.data.session.id; });
describe("session participant leave", () => { it("removes participant from waiting lobby and allows rejoin", async () => { expect((await playerAgent.post(`/api/sessions/${sessionId}/join`)).status).toBe(200); const left = await playerAgent.post(`/api/sessions/${sessionId}/leave`); expect(left.status).toBe(200); const state = await ownerAgent.get(`/api/sessions/${sessionId}`); expect(state.body.data.session.participantCount).toBe(0); const joinedAgain = await playerAgent.post(`/api/sessions/${sessionId}/join`); expect(joinedAgain.status).toBe(200); }); });
afterAll(async () => { if (sessionId) await prisma.quizSession.delete({ where: { id: sessionId } }); if (quizId) await prisma.quiz.delete({ where: { id: quizId } }); await prisma.user.delete({ where: { id: owner.id } }); await prisma.user.delete({ where: { id: player.id } }); await prisma.$disconnect(); });
