import express from "express";
import { z } from "zod";
import { requireAuth } from "../auth/auth.middleware.js";
import { realtimeIo } from "../realtime/socket.js";

const input = z.object({ quizId: z.number().int().positive() });
const fail = (res, status, code, message) => res.status(status).json({ error: { code, message, details: null } });
const pin = () => String(Math.floor(100000 + Math.random() * 900000));

export function createSessionRouter(prisma) {
  const router = express.Router(); router.use(requireAuth(prisma));
  router.post("/", async (req, res, next) => {
    const parsed = input.safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Некорректный quizId");
    try {
      const quiz = await prisma.quiz.findFirst({ where: { id: parsed.data.quizId, ownerUserId: req.user.id }, include: { questions: { include: { options: true } } } });
      if (!quiz) return fail(res, 404, "QUIZ_NOT_FOUND", "Квиз не найден");
      if (quiz.status !== "READY") return fail(res, 409, "QUIZ_NOT_READY", "Квиз не готов к запуску");
      const valid = quiz.questions.length > 0 && quiz.questions.every((q) => { const correct = q.options.filter((o) => o.isCorrect).length; return q.options.length >= 2 && q.options.length <= 6 && (q.type === "SINGLE_CHOICE" ? correct === 1 : correct >= 2 && correct < q.options.length); });
      if (!valid) return fail(res, 409, "QUIZ_NOT_READY", "Квиз не содержит валидных вопросов");
      const active = await prisma.quizSession.findFirst({ where: { quizId: quiz.id, status: { in: ["WAITING", "RUNNING"] } } });
      if (active) return fail(res, 409, "ACTIVE_SESSION_ALREADY_EXISTS", "Для этого квиза уже существует активная сессия");
      for (let attempt = 0; attempt < 10; attempt += 1) { try { const session = await prisma.quizSession.create({ data: { quizId: quiz.id, hostUserId: req.user.id, pin: pin(), status: "WAITING", phase: "READY_FOR_QUESTION", timeLimitSeconds: quiz.defaultTimeLimitSeconds, pointsPerQuestion: quiz.defaultPointsPerQuestion, revealCorrectAnswer: quiz.revealCorrectAnswer } }); return res.status(201).json({ data: { session: { id: session.id, quizId: session.quizId, quizTitle: quiz.title, pin: session.pin, status: session.status, phase: session.phase, participantCount: 0 } } }); } catch (error) { if (error?.code !== "P2002") throw error; } }
      return fail(res, 503, "PIN_GENERATION_FAILED", "Не удалось создать уникальный PIN");
    } catch (error) { if (error?.code === "P2002") return fail(res, 409, "ACTIVE_SESSION_ALREADY_EXISTS", "Для этого квиза уже существует активная сессия"); return next(error); }
  });
  router.get("/by-pin/:pin", async (req, res, next) => { try { const session = await prisma.quizSession.findFirst({ where: { pin: req.params.pin }, include: { quiz: true, host: true } }); if (!session) return fail(res, 404, "SESSION_NOT_FOUND", "Сессия не найдена"); if (session.status !== "WAITING") return fail(res, 409, session.status === "FINISHED" ? "SESSION_FINISHED" : "SESSION_ALREADY_STARTED", "Сессия уже началась или завершена"); return res.json({ data: { session: { id: session.id, quizTitle: session.quiz.title, hostDisplayName: session.host.displayName, status: session.status, canJoin: true } } }); } catch (e) { return next(e); } });
  router.post("/:sessionId/join", async (req, res, next) => { const id = Number(req.params.sessionId); try { const session = await prisma.quizSession.findUnique({ where: { id }, include: { host: true, participants: true } }); if (!session) return fail(res, 404, "SESSION_NOT_FOUND", "Сессия не найдена"); if (session.hostUserId === req.user.id) return fail(res, 403, "HOST_CANNOT_JOIN", "Ведущий не может присоединиться как участник"); if (session.status !== "WAITING") return fail(res, 409, session.status === "FINISHED" ? "SESSION_FINISHED" : "SESSION_ALREADY_STARTED", "Присоединение закрыто"); const existing = session.participants.find((item) => item.userId === req.user.id); const participant = existing ?? await prisma.sessionParticipant.create({ data: { quizSessionId: id, userId: req.user.id, displayNameSnapshot: req.user.displayName } }); if (!existing && realtimeIo) { const participants = await prisma.sessionParticipant.findMany({ where: { quizSessionId: id }, orderBy: { joinedAt: "asc" } }); realtimeIo.to(`session:${id}`).emit("participant:list", { participants: participants.map((item) => ({ id: item.id, displayName: item.displayNameSnapshot, isConnected: true, joinedAt: item.joinedAt.toISOString() })) }); realtimeIo.to(`session:${id}`).emit("participant:count", { participantCount: participants.length }); } return res.json({ data: { participant: { id: participant.id, sessionId: participant.quizSessionId, displayName: participant.displayNameSnapshot, joinedAt: participant.joinedAt.toISOString() }, rejoined: Boolean(existing) } }); } catch (e) { return next(e); } });
  router.get("/:sessionId", async (req, res, next) => { const id = Number(req.params.sessionId); try { const session = await prisma.quizSession.findUnique({ where: { id }, include: { quiz: true, participants: true } }); if (!session) return fail(res, 404, "SESSION_NOT_FOUND", "Сессия не найдена"); const participant = session.participants.find((p) => p.userId === req.user.id); if (session.hostUserId !== req.user.id && !participant) return fail(res, 403, "FORBIDDEN", "Нет доступа к сессии"); return res.json({ data: { session: { id: session.id, quizId: session.quizId, quizTitle: session.quiz.title, status: session.status, phase: session.phase, pin: session.hostUserId === req.user.id ? session.pin : undefined, participantCount: session.participants.length, isHost: session.hostUserId === req.user.id } } }); } catch (e) { return next(e); } });
  router.post("/:sessionId/cancel", async (req, res, next) => { const id = Number(req.params.sessionId); try { const session = await prisma.quizSession.findFirst({ where: { id, hostUserId: req.user.id } }); if (!session) return fail(res, 404, "SESSION_NOT_FOUND", "Сессия не найдена"); if (!["WAITING", "RUNNING"].includes(session.status)) return fail(res, 409, "INVALID_SESSION_STATE", "Сессию нельзя отменить в текущем состоянии"); const updated = await prisma.quizSession.update({ where: { id }, data: { status: "CANCELLED", phase: null, pin: null, cancelledAt: new Date() } }); if (realtimeIo) realtimeIo.to(`session:${id}`).emit("session:cancelled", { sessionId: id }); return res.json({ data: { sessionId: updated.id, status: updated.status } }); } catch (e) { return next(e); } });
  router.post("/:sessionId/leave", async (req, res, next) => { const id = Number(req.params.sessionId); try { const session = await prisma.quizSession.findUnique({ where: { id } }); if (!session) return fail(res, 404, "SESSION_NOT_FOUND", "Сессия не найдена"); if (session.status !== "WAITING") return fail(res, 409, "SESSION_ALREADY_STARTED", "Из активной игры выйти нельзя"); if (session.hostUserId === req.user.id) return fail(res, 403, "HOST_CANNOT_JOIN", "Ведущий не может покинуть lobby этим способом"); await prisma.sessionParticipant.deleteMany({ where: { quizSessionId: id, userId: req.user.id } }); if (realtimeIo) { const participants = await prisma.sessionParticipant.findMany({ where: { quizSessionId: id }, orderBy: { joinedAt: "asc" } }); realtimeIo.to(`session:${id}`).emit("participant:list", { participants: participants.map((item) => ({ id: item.id, displayName: item.displayNameSnapshot, isConnected: true, joinedAt: item.joinedAt.toISOString() })) }); realtimeIo.to(`session:${id}`).emit("participant:count", { participantCount: participants.length }); } return res.json({ data: { sessionId: id, left: true } }); } catch (e) { return next(e); } });
  return router;
}
