import { useEffect, useState } from "react";
import { Link, Outlet, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { AuthProvider, useAuth } from "./auth/AuthContext.jsx";
import ProtectedRoute from "./auth/ProtectedRoute.jsx";
import AuthPage from "./pages/AuthPage.jsx";
import QuestionForm from "./pages/QuestionForm.jsx";

function Home() { return <main className="app-shell"><section className="welcome-card"><h1>QuizTime</h1><Link to="/login">Войти</Link> <Link to="/register">Регистрация</Link></section></main>; }
function Dashboard() { const { user, logout } = useAuth(); const [quizzes, setQuizzes] = useState([]); useEffect(() => { fetch("/api/quizzes", { credentials: "include" }).then((r) => r.json()).then((b) => setQuizzes(b.data.quizzes)); }, []); return <main className="app-shell"><section className="welcome-card dashboard-card"><div className="dashboard-header"><div><p className="eyebrow">Личный кабинет</p><h1>Здравствуйте, {user.displayName}</h1></div><Link className="primary-link" to="/quizzes/new">Создать квиз</Link><button onClick={logout}>Выйти</button></div>{quizzes.map((q) => <article className="quiz-item" key={q.id}><strong>{q.title}</strong><Link to={`/quizzes/${q.id}/edit`}>Открыть</Link></article>)}</section></main>; }
function QuizEditor() { const { quizId } = useParams(); const navigate = useNavigate(); const editing = Boolean(quizId); const [categories, setCategories] = useState([]); const [questions, setQuestions] = useState([]); const [activeQuestion, setActiveQuestion] = useState(null); const [showQuestion, setShowQuestion] = useState(false); const [form, setForm] = useState({ title: "", description: "", categoryId: "", defaultTimeLimitSeconds: 30, defaultPointsPerQuestion: 1000, revealCorrectAnswer: true }); const [locked, setLocked] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([fetch("/api/categories", { credentials: "include" }).then((r) => r.json()), editing ? fetch(`/api/quizzes/${quizId}`, { credentials: "include" }).then((r) => r.json()) : Promise.resolve(null)]).then(([c, q]) => { setCategories(c.data.categories); if (q) { const x = q.data.quiz; setQuestions(x.questions ?? []); setLocked(x.isLocked); setForm({ title: x.title, description: x.description ?? "", categoryId: String(x.categoryId), defaultTimeLimitSeconds: x.defaultTimeLimitSeconds, defaultPointsPerQuestion: x.defaultPointsPerQuestion, revealCorrectAnswer: x.revealCorrectAnswer }); } }); }, [editing, quizId]);
  const remove = async (id) => { if (!window.confirm("Удалить вопрос?")) return; const r = await fetch(`/api/questions/${id}`, { method: "DELETE", credentials: "include" }); if (r.ok) setQuestions((items) => items.filter((x) => x.id !== id).map((x, i) => ({ ...x, position: i + 1 }))); };
  return <main className="app-shell"><section className="welcome-card editor-card"><div className="editor-header"><h1>Редактор квиза</h1><Link to="/dashboard">В кабинет</Link></div><form className="auth-form editor-form"><label>Название<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Описание<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>Категория<select value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })}><option value="">Выберите категорию</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button type="button" onClick={async () => { const r = await fetch(editing ? `/api/quizzes/${quizId}` : "/api/quizzes", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ ...form, categoryId: Number(form.categoryId) }) }); const b = await r.json(); if (r.ok) { setMessage("Сохранено"); navigate(`/quizzes/${b.data.quiz.id}/edit`); } }}>Сохранить черновик</button>{message && <p>{message}</p>}</form>{editing && <section className="questions-placeholder"><h2>Вопросы ({questions.length})</h2>{questions.map((q) => <article className="quiz-item" key={q.id}><strong>{q.position}. {q.text}</strong><button type="button" onClick={() => setActiveQuestion(q)}>Изменить</button><button type="button" onClick={() => remove(q.id)}>Удалить</button></article>)}{!locked && (activeQuestion ? <QuestionForm quizId={quizId} question={activeQuestion} onSaved={(q) => { setQuestions((items) => items.map((x) => x.id === q.id ? q : x)); setActiveQuestion(null); }} onCancel={() => setActiveQuestion(null)} /> : showQuestion ? <QuestionForm quizId={quizId} onSaved={(q) => { setQuestions((items) => [...items, { ...q, position: items.length + 1 }]); setShowQuestion(false); }} onCancel={() => setShowQuestion(false)} /> : <button type="button" onClick={() => setShowQuestion(true)}>Добавить вопрос</button>)}</section>}</section></main>; }
export default function App() { return <AuthProvider><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/register" element={<AuthPage mode="register" />} /><Route element={<ProtectedRoute />}><Route path="/dashboard" element={<Dashboard />} /><Route path="/quizzes/new" element={<QuizEditor />} /><Route path="/quizzes/:quizId/edit" element={<QuizEditor />} /></Route><Route path="*" element={<Outlet />} /></Routes></AuthProvider>; }
