import { useEffect, useState } from "react";
import { Link, Outlet, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { AuthProvider, useAuth } from "./auth/AuthContext.jsx";
import ProtectedRoute from "./auth/ProtectedRoute.jsx";
import AuthPage from "./pages/AuthPage.jsx";

function Home() { return <main className="app-shell"><section className="welcome-card"><p className="eyebrow">QuizTime</p><h1>Интерактивные квизы в реальном времени</h1><p>Войдите в аккаунт, чтобы создавать квизы и играть.</p><Link to="/login">Войти</Link> <Link to="/register">Регистрация</Link></section></main>; }

function Dashboard() {
  const { user, logout } = useAuth(); const [tab, setTab] = useState("quizzes"); const [quizzes, setQuizzes] = useState([]); const [state, setState] = useState("loading");
  useEffect(() => { fetch("/api/quizzes", { credentials: "include" }).then(async (r) => { if (!r.ok) throw new Error(); return r.json(); }).then((b) => { setQuizzes(b.data.quizzes); setState("ready"); }).catch(() => setState("error")); }, []);
  return <main className="app-shell"><section className="welcome-card dashboard-card"><div className="dashboard-header"><div><p className="eyebrow">Личный кабинет</p><h1>Здравствуйте, {user.displayName}</h1><p>{user.email}</p></div><div className="header-actions"><Link className="primary-link" to="/quizzes/new">Создать квиз</Link><button type="button" onClick={logout}>Выйти</button></div></div><nav className="tabs"><button className={tab === "quizzes" ? "active" : ""} onClick={() => setTab("quizzes")}>Мои квизы</button><button className={tab === "hosted" ? "active" : ""} onClick={() => setTab("hosted")}>Проведённые игры</button><button className={tab === "participations" ? "active" : ""} onClick={() => setTab("participations")}>История участия</button></nav>{tab === "quizzes" && (state === "loading" ? <p>Загрузка квизов…</p> : state === "error" ? <p role="alert">Не удалось загрузить квизы.</p> : quizzes.length === 0 ? <p>У вас пока нет квизов.</p> : <div className="quiz-list">{quizzes.map((quiz) => <article className="quiz-item" key={quiz.id}><div><h2>{quiz.title}</h2><p>{quiz.category.name} · {quiz.questionCount} вопросов</p></div><div className="quiz-item-actions"><span>{quiz.status}</span><Link to={`/quizzes/${quiz.id}/edit`}>Открыть</Link></div></article>)}</div>)}{tab === "hosted" && <p>Проведённых игр пока нет.</p>}{tab === "participations" && <p>История участия пока пуста.</p>}</section></main>;
}

function QuizEditor() {
  const { quizId } = useParams(); const navigate = useNavigate(); const editing = Boolean(quizId);
  const [categories, setCategories] = useState([]); const [form, setForm] = useState({ title: "", description: "", categoryId: "", defaultTimeLimitSeconds: 30, defaultPointsPerQuestion: 1000, revealCorrectAnswer: true }); const [state, setState] = useState(editing ? "loading" : "ready"); const [message, setMessage] = useState(""); const [locked, setLocked] = useState(false);
  useEffect(() => { Promise.all([fetch("/api/categories", { credentials: "include" }).then((r) => r.json()), editing ? fetch(`/api/quizzes/${quizId}`, { credentials: "include" }).then((r) => r.json()) : Promise.resolve(null)]).then(([c, q]) => { setCategories(c.data.categories); if (q) { const x = q.data.quiz; setForm({ title: x.title, description: x.description ?? "", categoryId: String(x.categoryId), defaultTimeLimitSeconds: x.defaultTimeLimitSeconds, defaultPointsPerQuestion: x.defaultPointsPerQuestion, revealCorrectAnswer: x.revealCorrectAnswer }); setLocked(x.isLocked); } setState("ready"); }).catch(() => setState("error")); }, [editing, quizId]);
  const update = (e) => setForm((f) => ({ ...f, [e.target.name]: e.target.type === "checkbox" ? e.target.checked : e.target.value }));
  const submit = async (e) => { e.preventDefault(); setMessage(""); setState("saving"); const body = { ...form, categoryId: Number(form.categoryId), defaultTimeLimitSeconds: Number(form.defaultTimeLimitSeconds), defaultPointsPerQuestion: Number(form.defaultPointsPerQuestion) }; const r = await fetch(editing ? `/api/quizzes/${quizId}` : "/api/quizzes", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify(body) }); const b = await r.json(); if (!r.ok) { setMessage(b.error?.message ?? "Не удалось сохранить квиз"); setState("ready"); return; } setState("ready"); setMessage("Изменения сохранены"); navigate(`/quizzes/${b.data.quiz.id}/edit`); };
  if (state === "loading") return <main className="app-shell"><section className="welcome-card"><p>Загрузка редактора…</p></section></main>; if (state === "error") return <main className="app-shell"><section className="welcome-card"><p role="alert">Не удалось загрузить редактор.</p><Link to="/dashboard">В кабинет</Link></section></main>;
  return <main className="app-shell"><section className="welcome-card editor-card"><div className="editor-header"><div><p className="eyebrow">Редактор квиза</p><h1>{editing ? "Настройки квиза" : "Новый квиз"}</h1></div><Link to="/dashboard">В кабинет</Link></div>{locked && <p className="notice">Квиз уже использовался в игре и доступен только для просмотра.</p>}<form className="auth-form editor-form" onSubmit={submit}><label>Название<input name="title" value={form.title} onChange={update} required disabled={locked || state === "saving"} /></label><label>Описание<textarea name="description" value={form.description} onChange={update} disabled={locked || state === "saving"} /></label><label>Категория<select name="categoryId" value={form.categoryId} onChange={update} required disabled={locked || state === "saving"}><option value="">Выберите категорию</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="editor-grid"><label>Время (сек.)<input type="number" name="defaultTimeLimitSeconds" min="5" max="120" value={form.defaultTimeLimitSeconds} onChange={update} disabled={locked} /></label><label>Баллы<input type="number" name="defaultPointsPerQuestion" min="100" max="5000" value={form.defaultPointsPerQuestion} onChange={update} disabled={locked} /></label></div><label className="checkbox-label"><input type="checkbox" name="revealCorrectAnswer" checked={form.revealCorrectAnswer} onChange={update} disabled={locked} /> Показывать правильный ответ</label>{message && <p role="alert">{message}</p>}{!locked && <button type="submit" disabled={state === "saving"}>{state === "saving" ? "Сохранение…" : "Сохранить черновик"}</button>}</form>{editing && <div className="questions-placeholder"><h2>Вопросы</h2><p>Редактор вопросов будет добавлен на Этапе 4.</p></div>}</section></main>;
}

export default function App() { return <AuthProvider><Routes><Route path="/" element={<Home />} /><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/register" element={<AuthPage mode="register" />} /><Route element={<ProtectedRoute />}><Route path="/dashboard" element={<Dashboard />} /><Route path="/quizzes/new" element={<QuizEditor />} /><Route path="/quizzes/:quizId/edit" element={<QuizEditor />} /></Route><Route path="*" element={<Outlet />} /></Routes></AuthProvider>; }
