import { useEffect, useState } from "react";
import { Link, Outlet, Route, Routes, useNavigate, useParams } from "react-router-dom";
import { AuthProvider, useAuth } from "./auth/AuthContext.jsx";
import ProtectedRoute from "./auth/ProtectedRoute.jsx";
import AuthPage from "./pages/AuthPage.jsx";
import QuestionForm from "./pages/QuestionForm.jsx";
import LobbyPage from "./pages/LobbyPage.jsx";
import StartSessionPage from "./pages/StartSessionPage.jsx";
import JoinSessionPage from "./pages/JoinSessionPage.jsx";
function Home() { return <main className="app-shell"><section className="welcome-card"><h1>QuizTime</h1><p>Чтобы присоединиться к игре, войдите в аккаунт и используйте кнопку «Присоединиться по PIN» в личном кабинете.</p><Link to="/login">Войти</Link> <Link to="/register">Регистрация</Link></section></main>; }
function Dashboard() { const { user, logout } = useAuth(); const [quizzes, setQuizzes] = useState([]); useEffect(() => { fetch("/api/quizzes", { credentials: "include" }).then((r) => r.json()).then((b) => setQuizzes(b.data.quizzes)); }, []); return <main className="app-shell"><section className="welcome-card dashboard-card"><div className="dashboard-header"><div><p className="eyebrow">Личный кабинет</p><h1>Здравствуйте, {user.displayName}</h1></div><div className="header-actions"><Link className="primary-link" to="/quizzes/new">Создать квиз</Link><Link className="primary-link" to="/join">Присоединиться по PIN</Link><button onClick={logout}>Выйти</button></div></div>{quizzes.map((q) => <article className="quiz-item" key={q.id}><div><strong>{q.title}</strong><p>{q.category.name} · {q.questionCount} вопросов · {q.status}</p></div><div className="quiz-item-actions"><Link to={`/quizzes/${q.id}/edit`}>Открыть</Link>{q.status === "READY" && <Link to={`/sessions/start/${q.id}`}>Запустить игру</Link>}</div></article>)}</section></main>; }
function QuizEditor() { const { quizId } = useParams(); const navigate = useNavigate(); const editing = Boolean(quizId); const [categories, setCategories] = useState([]); const [questions, setQuestions] = useState([]); const [show, setShow] = useState(false); const [form, setForm] = useState({ title: "", description: "", categoryId: "" }); useEffect(() => { Promise.all([fetch("/api/categories", { credentials: "include" }).then((r) => r.json()), editing ? fetch(`/api/quizzes/${quizId}`, { credentials: "include" }).then((r) => r.json()) : Promise.resolve(null)]).then(([c, q]) => { setCategories(c.data.categories); if (q) { const x = q.data.quiz; setQuestions(x.questions); setForm({ title: x.title, description: x.description ?? "", categoryId: String(x.categoryId) }); } }); }, [editing, quizId]); const save = async (e) => { e.preventDefault(); const r = await fetch(editing ? `/api/quizzes/${quizId}` : "/api/quizzes", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, credentials: "include", body: JSON.stringify({ ...form, categoryId: Number(form.categoryId), defaultTimeLimitSeconds: 30, defaultPointsPerQuestion: 1000, revealCorrectAnswer: true }) }); const b = await r.json(); if (r.ok) navigate(`/quizzes/${b.data.quiz.id}/edit`); }; return <main className="app-shell"><section className="welcome-card editor-card"><Link to="/dashboard">В кабинет</Link><h1>Редактор квиза</h1><form className="auth-form editor-form" onSubmit={save}><label>Название<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Описание<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label>Категория<select value={form.categoryId} onChange={(e) => setForm({ ...form, categoryId: e.target.value })}><option value="">Выберите категорию</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><button>Сохранить черновик</button></form>{editing && <section className="questions-placeholder"><h2>Вопросы ({questions.length})</h2>{questions.map((q) => <p key={q.id}>{q.position}. {q.text}</p>)}{show ? <QuestionForm quizId={quizId} onSaved={(q) => { setQuestions([...questions, q]); setShow(false); }} onCancel={() => setShow(false)} /> : <button type="button" onClick={() => setShow(true)}>Добавить вопрос</button>}</section>}</section></main>; }
export default function App() { return <AuthProvider><Routes><Route path="/" element={<Home />} /><Route path="/join" element={<JoinSessionPage />} /><Route path="/login" element={<AuthPage mode="login" />} /><Route path="/register" element={<AuthPage mode="register" />} /><Route element={<ProtectedRoute />}><Route path="/dashboard" element={<Dashboard />} /><Route path="/quizzes/new" element={<QuizEditor />} /><Route path="/quizzes/:quizId/edit" element={<QuizEditor />} /><Route path="/sessions/start/:quizId" element={<StartSessionPage />} /><Route path="/sessions/:sessionId/host" element={<LobbyPage />} /><Route path="/play/:sessionId" element={<LobbyPage />} /></Route><Route path="*" element={<Outlet />} /></Routes></AuthProvider>; }
